### ISSUE TITLE
[FR] Word Vectors -> TSNE -> bokeh.html function that can be composed in the middle of the pipeline.

### ISSUE THREAD

**Issue by finnkauski** [datasciencecampus/woffle#19]
**Is your feature request related to a problem? Please describe.**
We might need a function that could be inserted into the composition which provides a TSNE reduced plot as a bokeh.html of the embeddings.

**Describe the solution you'd like**
A simple function that does TSNE from sklearn and outputs a bokeh interactive visualization html file. I would propose the first implementation to use a sample of the data.

**Additional context**
We've done it before so its a simple reuse of code. And once we start looking into the vectors we get out based on what data we use it will come in handy.

**Comment by karetsu** [comment]
Committed in 6d0a5589b28d087756d00b4830782a3147e69fa9 - removed for now because issues with statefulness, will pick it out of the commit later and fix it up then.

**Comment by karetsu** [comment]
-DEPRECATED-

Development will be put on hold until there is a need for more NLP development, so this has been deprioritised for now
