### ISSUE TITLE
[FR] using cytoolz as a functools replacement

### ISSUE THREAD

**Issue by mamonu** [datasciencecampus/woffle#21]
Just a suggestion really. 

Perhaps use cytoolz as a functools replacement library on
https://github.com/karetsu/woffle/blob/master/woffle/functions/compose.py

cytools is itself a cython based toolz replacement library

toolz is a replacement of itertools functools etc with some extras

**Comment by karetsu** [comment]
Parking for now, to re-open if there is interest in the project and run times increase.
